version: "3.8"

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://user-service:3000
    networks:
      - public_net
      - service_net

  user-service:
    build: ./services/user-service
    networks:
      - service_net

networks:
  public_net:
    driver: bridge

  service_net:
    driver: bridge