{
 "title": "System",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "count(process_cpu_seconds_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API GatewayTotal Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "gateway_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HoneypotTotal Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "honeypot_suspicious_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(honeypot_suspicious_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Methods Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by (method) (rate(honeypot_suspicious_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}